### ISSUE TITLE
Can't working under Grafana 3.0.1

### ISSUE THREAD

**Issue by qindj** [bosun-monitor/bosun-grafana-datasource#1]
Hi, Admin

I used this plugin to show graph in Grafana, but in Grafana 3.0.1, it doesn;t work, error shows as following:

![image](https://cloud.githubusercontent.com/assets/1707762/15217697/57d77440-188f-11e6-9976-1d9a8a2d6840.png)

the same issue as #https://github.com/grafana/grafana/issues/4995

do you have any plan to fix it? thanks very much!

**Comment by prajwalrao** [comment]
@qindj https://github.com/bosun-monitor/bosun-grafana-datasource/pull/2 - this should help you..

**Comment by qindj** [comment]
@prajwalrao  thank you very much!

**Comment by yuyuntao** [comment]
It works! Thank you very much!

**Comment by vitorboschi** [comment]
PR merged and improved in commit 54270726ea1c1cc12777acc32634292ff8055a70
Thanks for reporting!
