### ISSUE TITLE
[Feature Request] Fill template variables dynamically

### ISSUE THREAD

**Issue by d10v** [bosun-monitor/bosun-grafana-datasource#9]
There's http://docs.grafana.org/reference/templating/#query feature to populate template variables dynamically from Data Source query. It would be really nice to have. Thanks.

**Comment by kylebrandt** [comment]
Done, but needs documentation

**Comment by vitorboschi** [comment]
Implemented by https://github.com/bosun-monitor/bosun-grafana-datasource/commit/1b654ac4d170a86aacaf5544ca9d1dde453fa5a8

You can fill the query field with `tagkeys(metric.name)` or `tagvalues(metric.name, tagvalue)` to get tag values and tag keys available.

**Comment by vitorboschi** [comment]
There are now some documentation on README.md
